import os, requests, json
import logging
import streamlit as st

class AuthTokenHandler:

    def __init__(self):

        self.firebase_config_api_key = os.environ.get("FIREBASE_API_KEY","")

        if not self.firebase_config_api_key:
            # Hide sidebar
            st.markdown("""
                    <style>
                        [data-testid="stSidebar"], [data-testid="collapsedControl"] {display: none;}
                        body {background-color: #f6f7fb;}
                        div[data-testid="stForm"] {box-shadow:none !important;}
                        div.block-container{padding-top:5vh;}
                        .gustavo-title{
                            text-align:center;
                            font-weight:700;
                            font-size:1.1rem;
                            color:#1f1f2e;
                            margin-top:1rem;
                        }
                        .gustavo-subtitle{
                            text-align:center;
                            color:#5e5e75;
                            font-size:0.85rem;
                            margin-bottom:1.5rem;
                        }
                        div.stButton>button:first-child{
                            background-color:#1f1f2e;
                            color:white;
                            border-radius:0.4rem;
                            height:2.5rem;
                            width:100%;
                            font-weight:600;
                            border:none;
                        }
                        div.stButton>button:hover{background-color:#2b2b45;}
                    </style>
                """, unsafe_allow_html=True)
            st.error("Auth has been enabled but FIREBASE_API_KEY is not set in env_var")
            st.stop()
            #raise Exception("Auth has been enabled but FIREBASE_API_KEY is not set in env_var")

        self.id_token = None

        # Replace with your server endpoint
        if "EMULATE_FIREBASE" in os.environ.keys():
            self.AUTH_ENDPOINT = "http://127.0.0.1:8071/blockalytics-6ebbb/us-central1/datachat"

        else:
            self.AUTH_ENDPOINT = 'https://us-central1-blockalytics-6ebbb.cloudfunctions.net/datachat'

        self.error_cases = {
            400: ("BadRequest", "The request was invalid or cannot be served"),
            401: ("Unauthorized",
                  "Authentication is required to access this feature. Ensure Scarlet DataChat is enabled and user token is valid."),
            403: ("Forbidden", "You do not have permission to access this resource"),
            404: ("NotFound", "The requested resource could not be found"),
            405: ("MethodNotAllowed", "The HTTP method used is not allowed for this resource"),
            408: ("RequestTimeout", "The DataChat backend server timed out waiting for the request"),
            409: ("Conflict", "The request could not be completed due to a conflict"),
            410: ("Gone", "The requested resource is no longer available"),
            413: ("PayloadTooLarge", "The request payload is too large"),
            415: ("UnsupportedMediaType", "The request media type is not supported"),
            422: ("UnprocessableEntity", "The request was well-formed but contained invalid data"),
            429: ("TooManyRequests", "You have sent too many requests in a given amount of time"),
            500: ("InternalServerError", "Something went wrong on the DataChat backend server, Try again in sometime."),
            501: ("NotImplemented", "The requested functionality is not supported by DataChat backend"),
            502: ("BadGateway", "The DataChat backend server received an invalid AI response"),
            # The DataChat backend server received an invalid response from an upstream server
            503: ("ServiceUnavailable", "The DataChat backend server is temporarily unable to handle the request"),
            # "The server did not receive a timely response from an upstream server"
            504: ("GatewayTimeout", "Trouble invoking DataChat backend server. Try again in sometime."),
        }

    def get_custom_token(self,user_id, user_token):
        """
        Authenticate a user with Firebase using a Keygen user ID and token.
        This method retrieves a custom token that can be used in place of an ID token for specific operations within the client.
        The custom token is automatically generated by this client based on Keygen user ID and token.

        Parameters
        ----------
        user_id: str
            The user id for whom the token needs to be generated for.

        user_token: str
            The keygen user token with which to get a Firebase token.

        Returns
        -------
        tuple[bool, Optional[str]]
            On success:
                - status : bool indicating whether the operation succeeded
                - token : A string containing the generated ID token

            On failure:
                - status : False
                - error : An error response object (see `self.returnError` for details)
        """

        # Send user ID and token to your server endpoint
        try:
            # Send user ID and token to your server endpoint
            json_data = json.dumps({'user_id': user_id, 'user_token': user_token})
            response = requests.post(
                f"{self.AUTH_ENDPOINT}/getAuthToken",
                data=json_data,
                headers={'Content-type': 'application/json'}
            )
            if response.status_code == 200:
                data = response.json()
                firebase_token = data.get('firebase_token')

                if firebase_token:
                    logging.info('Successfully authenticated')
                    return True, firebase_token
                else:
                    logging.critical('Failed to retrieve Firebase token')
                    return False, None
            else:
                response_json = response.json()
                logging.critical(f"Error: {response_json}", )
                return False, None

        except Exception as e:
            logging.critical('Exception occurred:', e)
            return False, None

    def exchange_custom_with_id_token(self,custom_token):
        """
        This method is used to replace the custom token with an ID token from firebase.
        This allows you to use a custom token for specific operations within the client.

        Parameters
        ----------
        custom_token: str
            The custom token string to be used for exchanging with the ID token.

        Returns
        -------
        tuple[bool, Optional[str]]
            On success:
                - status : bool indicating whether the operation succeeded
                - token : A string containing the generated ID token

            On failure:
                - status : False
                - error : An error response object (see `self.returnError` for details)
        """
        FIREBASE_API_KEY = self.firebase_config_api_key

        url = f"https://identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken?key={FIREBASE_API_KEY}"
        payload = {
            "token": custom_token,
            "returnSecureToken": True
        }
        response = requests.post(url, json=payload)

        if response.status_code == 200:
            tokens = response.json()
            id_token = tokens.get("idToken")  # This token will be used for server interactions
            return True, id_token
        else:
            logging.critical("Error exchanging custom token:", response.json())
            return False, None
