# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Package Creation

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
             os: [ubuntu-22.04]
             python-version: [ 3.10.0 , 3.8.0 , 3.7.2 ]
    if: "contains(github.event.head_commit.message, '#buildpackage')" 
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        WITH_V: true
    - name: Build Package files
      working-directory: ./
      env:
        SUPER_SECRET: ${{ secrets.GIT_INFO }}
        GEMFURY_TOKEN: ${{ secrets.GEMFURY_TOKEN }}
      run: |
        pip install wheel
        pip install -r requirements.txt
        python3 builder.py "$SUPER_SECRET" "$GEMFURY_TOKEN"







