#[theme]
#primaryColor="#0793f0"
#backgroundColor="#FFFFFF"
#secondaryBackgroundColor="#F0F2F6"
#textColor="#262730"
#font="sans serif"

[ui]
hideTopBar = false

[client]
showSidebarNavigation = false
