version: '3'

services:
  gustavo_comm_test:
    container_name: gustavo_comm_test
    image: "nasahomert2/gustavo_comm_test:v0.2.0-beta.14"
    restart: always
    network_mode: "host"
    volumes:
      - /tmp/:/tmp/
    environment:
      - REDIS_DB_HOST=10.219.128.99
      - REDIS_DB_PORT=6379
      - REDIS_DB_PWD=e87052bfcc0b65b2d0603ad4baa8d8ced7aa929b6698a568d2ce53dfd2dc04bcs
    command: bash -c "python3 /home/tests/comms_manager.py"